version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

jobs:
  security-scans:
    resource_class: small
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - prodsec/security_scans:
          mode: auto
          open-source-additional-arguments: --exclude=test
          release-branch: master
          iac-scan: disabled
          debug: true

workflows:
  version: 2
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: snyk-on-snyk-devex_ide

      - security-scans:
          context: devex_ide
