//
//  DestinationsOptions.java
//  This file is auto-generated by Iteratively. Run `itly pull jetbrains` to update.
//

package snyk.analytics;

import ly.iterative.itly.IterativelyOptions;

public class DestinationsOptions {
    IterativelyOptions iteratively;

    private DestinationsOptions(Builder builder) {
       this.iteratively = builder.iteratively;
    }

    public static IIteratively builder() {
        return new Builder();
    }

    public static class Builder implements IIteratively, IBuild {
        IterativelyOptions iteratively;

        private Builder() {}

        public Builder iteratively(IterativelyOptions iteratively) {
            this.iteratively = iteratively;
            return this;
        }
        public DestinationsOptions build() {
            return new DestinationsOptions(this);
        }
    }

    public interface IIteratively {
        Builder iteratively(IterativelyOptions iteratively);
    }

    public interface IBuild {
        DestinationsOptions build();
    }
}
