//
//  ProductSelectionIsViewed.java
//  This file is auto-generated by Iteratively. Run `itly pull jetbrains` to update.
//

package snyk.analytics;

import java.util.HashMap;

import ly.iterative.itly.Event;

public class ProductSelectionIsViewed extends Event {
    private static final String NAME = "Product Selection Is Viewed";
    private static final String ID = "4817979a-5fa1-4d1c-9418-2c28471c682d";
    private static final String VERSION = "4.0.0";

    public enum Ide {
        VISUAL_STUDIO_CODE("Visual Studio Code"), VISUAL_STUDIO("Visual Studio"), ECLIPSE("Eclipse"), JETBRAINS("JetBrains");

        private String ide;

        public String getIde()
        {
            return this.ide;
        }

        Ide(String ide)
        {
            this.ide = ide;
        }
    }

    private ProductSelectionIsViewed(Builder builder) {
        super(NAME, builder.properties, ID, VERSION);
    }

    private ProductSelectionIsViewed(ProductSelectionIsViewed clone) {
        super(NAME, new HashMap<>(clone.getProperties()), ID, VERSION);
    }

    public ProductSelectionIsViewed clone() {
        return new ProductSelectionIsViewed(this);
    }

    public static IIde builder() { return new Builder(); }

    // Inner Builder class with required properties
    public static class Builder implements IIde, IBuild {
        private final HashMap<String, Object> properties = new HashMap<String, Object>();

        private Builder() {
            this.properties.put("itly", true);
        }

        /**
         * Ide family.
         * <p>
         * Must be followed by by additional optional properties or build() method
         */
        public Builder ide(Ide ide) {
            this.properties.put("ide", ide.getIde());
            return this;
        }

        public ProductSelectionIsViewed build() {
            return new ProductSelectionIsViewed(this);
        }
    }

    // Required property interfaces
    public interface IIde {
        Builder ide(Ide ide);
    }

    /** Build interface with optional properties */
    public interface IBuild {
        ProductSelectionIsViewed build();
    }
}
