name: Weekly Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 1'  # every Monday at 10 am UTC

jobs:
  create-release-tag:
    name: create release tag
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Release
        if: ${{ !env.ACT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout master
          ./gradlew release

      - name: Release - Dry Run
        if: ${{ env.ACT }}
        run: ./gradlew release -Prelease.dryRun

