package snyk.common.lsp.commands

internal const val COMMAND_EXECUTE_CLI = "snyk.executeCLI"
internal const val COMMAND_REPORT_ANALYTICS = "snyk.reportAnalytics"
internal const val COMMAND_GET_FEATURE_FLAG_STATUS = "snyk.getFeatureFlagStatus"
internal const val COMMAND_WORKSPACE_FOLDER_SCAN = "snyk.workspaceFolder.scan"
internal const val COMMAND_GET_ACTIVE_USER = "snyk.getActiveUser"
internal const val COMMAND_LOGIN = "snyk.login"
internal const val COMMAND_LOGOUT = "snyk.logout"
internal const val COMMAND_GET_SETTINGS_SAST_ENABLED = "snyk.getSettingsSastEnabled"
internal const val COMMAND_COPY_AUTH_LINK = "snyk.copyAuthLink"
internal const val COMMAND_CODE_FIX_DIFFS = "snyk.code.fixDiffs"
internal const val COMMAND_CODE_FIX_APPLY_AI_EDIT = "snyk.code.fixApplyEdit"
internal const val SNYK_GENERATE_ISSUE_DESCRIPTION = "snyk.generateIssueDescription"
internal const val COMMAND_SUBMIT_IGNORE_REQUEST = "snyk.submitIgnoreRequest"
